/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ChAlert: typeof import('./components/cues/ChAlert.vue')['default']
    ChAvatar: typeof import('./components/core/ChAvatar.vue')['default']
    ChBadge: typeof import('./components/core/ChBadge.vue')['default']
    ChButton: typeof import('./components/core/ChButton.vue')['default']
    ChCard: typeof import('./components/core/ChCard.vue')['default']
    ChChart: typeof import('./components/data/ChChart.vue')['default']
    ChCheckbox: typeof import('./components/forms/ChCheckbox.vue')['default']
    ChDataList: typeof import('./components/data/ChDataList.vue')['default']
    ChDatePicker: typeof import('./components/forms/ChDatePicker.vue')['default']
    ChDivider: typeof import('./components/core/ChDivider.vue')['default']
    ChFileUpload: typeof import('./components/forms/ChFileUpload.vue')['default']
    ChFormField: typeof import('./components/forms/ChFormField.vue')['default']
    ChInput: typeof import('./components/core/ChInput.vue')['default']
    ChModal: typeof import('./components/forms/ChModal.vue')['default']
    ChPagination: typeof import('./components/data/ChPagination.vue')['default']
    ChProgress: typeof import('./components/cues/ChProgress.vue')['default']
    ChPullToRefresh: typeof import('./components/cues/ChPullToRefresh.vue')['default']
    ChRadio: typeof import('./components/forms/ChRadio.vue')['default']
    ChSelect: typeof import('./components/forms/ChSelect.vue')['default']
    ChSidebar: typeof import('./components/navigation/ChSidebar.vue')['default']
    ChSidebarItem: typeof import('./components/navigation/ChSidebarItem.vue')['default']
    ChSkeleton: typeof import('./components/cues/ChSkeleton.vue')['default']
    ChSlider: typeof import('./components/forms/ChSlider.vue')['default']
    ChSpinner: typeof import('./components/cues/ChSpinner.vue')['default']
    ChStatCard: typeof import('./components/data/ChStatCard.vue')['default']
    ChStepperStep: typeof import('./components/forms/ChStepperStep.vue')['default']
    ChStepperWizard: typeof import('./components/forms/ChStepperWizard.vue')['default']
    ChSwitch: typeof import('./components/forms/ChSwitch.vue')['default']
    ChTable: typeof import('./components/data/ChTable.vue')['default']
    ChTableExportDialog: typeof import('./components/data/ChTableExportDialog.vue')['default']
    ChTabs: typeof import('./components/navigation/ChTabs.vue')['default']
    ChTextarea: typeof import('./components/core/ChTextarea.vue')['default']
    ChTimeline: typeof import('./components/forms/ChTimeline.vue')['default']
    ChTimelineItem: typeof import('./components/forms/ChTimelineItem.vue')['default']
    ChToast: typeof import('./components/cues/ChToast.vue')['default']
    ChToastContainer: typeof import('./components/cues/ChToastContainer.vue')['default']
    ChTopbar: typeof import('./components/navigation/ChTopbar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
